accounts/urls.py
from urllib.parse import urlparse
from django.conf.urls import url 
from django.contrib.auth import views as auth_views 
from . import views 
app_name='accounts'
urlpatterns = [
    url(r'login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),

]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include 
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view()),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),

]

accounts/models.py
from django.db import models
from django.contrib import auth 

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.db import models
from django.utils.text import slugify 
# Create your models here.
import misaka
from django.contrib.auth import get_user_model 
User=get_user_model() 
from django import template 
register=template.Library() 
class Group(models.Model):
    name=models.CharField(max_length=255,unique=True)
    slug=models.SlugField(allow_unicode=True,unique=True)
class GroupMember(models.Model):
    group=models.ForeignKey(Group,related_name='membership')
    user=models.ForeignKey(User,related_name='user_groups')
    def __str__(self):
        return self.user.username 
    class Meta:
        unique_together=('group','user')


    pass 

posts/models.py
from django.db import models

# Create your models here.

forms.py
from django.contrib.auth import get_user_model 
from django.contrib.auth.forms import UserCreationForm 
class UserCreateForm(UserCreationForm):
    class Meta:
        field=('username','email','password1','password2')
        model=get_user_model()
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label='Display Name'
        self.fields['email'].label='Email Address'
        

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
# Create your views here.
class SignUp(CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('login')
    template_name= 'accounts/signup.html'

groups/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render

# Create your views here.

simplesocial/views.py
from django.views.generic import TemplateView 
class TestPage(TemplateView):
    template_name='test.html'
class ThanksPage(TemplateView):
    template_name='thanks.html'
    
class HomePage(TemplateView):
    template_name='index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"class="btn btn-default" name="" value="Log In">

    <form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit"class="btn btn-default" name="" value="Sign Up">

    <form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Star Social</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
    </head>
    <body>
        <nav class="navbar mynav" role='navigation' id='navbar'>
            <div class="container">
                <a class='navbar-brand mynav'>Star Social</a>
                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}
                    <li><a href="#">Post</a></li>
                    <li><a href="#">Groups</a></li>
                    <li><a href="#">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href='#'>Groups</a></li>
                    <li><a href='{% url 'accounts:login' %}'>Log In</a></li>
                    <li><a href='{% url 'accounts:signup'%}'>Sign Up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to Star Social!</h1>
{% endblock %}
    

templates/test.html
{% extends "base.html"%}
{% block content %}
<h1>You are now logged in!</h1> 

{% endblock %}

templates/thanks.html
{% extends "base.html"%}
{% block content %}
<h1>Thanks for visting, come back soon!</h1> 

{% endblock %}